    name: geomaptools
    main: de.cndrbrbr.mc.geomaptools
    author: cndrbrbr
    description: because it is possible
    version: 4.34
    commands:
        gspur:
            description: Mache eine Spur aus Material. [material = coal,gold,diamond,dirt,fence,glass,sand,grass,redstoneblock,glowstone,gravel,poweredrail,potato,apple]
            usage: /<command> [material=gold]  Dicke der Spur(hoehe=1)  material = coal,gold,diamond,dirt,fence,glass,sand,grass,redstoneblock,glowstone,gravel,poweredrail,potato,apple
            permission: geomaptools.basic
            permission-message: You don't have <permission>
        goff:
            description: geoTools off for <player>
            usage: /<command> 
            permission: geomaptools.basic
            permission-message: You don't have <permission>
        gquad:
            description: Mache 4 Bloecke. [material = coal,gold,diamond,dirt,fence,glass,sand,grass,redstoneblock,glowstone,gravel,poweredrail,potato,apple]
            usage: /<command> [material] breite hoehe tiefe  material = coal,gold,diamond,dirt,fence,glass,sand,grass,redstoneblock,glowstone,gravel,poweredrail,potato,apple]
            permission: geomaptools.basic
            permission-message: You don't have <permission>
        gforward:
            description: Setzt eine <hoehe> Block hohe Mauer <laenge> geradeaus.
            usage: /<command> [laenge der Mauer] [hoehe der Mauer]
            permission: geomaptools.basic
            permission-message: You don't have <permission>
        gmap:
            description: Setzt eine Karte ein.
            usage: /<command> rechtsclick
            permission: geomaptools.advanced
            permission-message: You don't have <permission>
        gload:
            description: laedt ein bild.
            usage: /<command> 
            permission: geomaptools.advanced
            permission-message: You don't have <permission>
        glist:
            description: Listet alle Bilder namen.
            usage: /<command> 
            permission: geomaptools.advanced
            permission-message: You don't have <permission>       
        gdelete:
            description: loescht alle angrenzenden Bloecke, die dasselbe Material haben, wie der selektierte. In der Hand muss das Material auch sein.
            usage: /<command> radius 
            permission: geomaptools.advanced
            permission-message: You don't have <permission>
        gOSMOverpass:
            description: Importiert die Karte von Open Street Map
            usage: /<command> breite und tiefe in Meter ab dem selektierten Block
            permission: geomaptools.basic
            permission-message: You don't have <permission>
        gbuildalong:
            description: baut mit dem geclickten material des geclickten blocks eine wand mit hoehe h im radius r
            usage: /<command> radius hoehe 
            permission: geomaptools.advanced
            permission-message: You don't have <permission>
        gspawnColorSheeps:
            description: Spawnt bunte Schafe, wenn keine Farbean gegeben, bunte Schafe jeb_
            usage: /<command> Anzahl Farbe (WHITE ORANGE MAGENTA LIGHT_BLUE YELLOW LIME PINK GRAY SILVER CYAN PURPLE BLUE BROWN GREEN RED BLACK)
            permission: geomaptools.basic
            permission-message: You don't have <permission>
    
    